### ISSUE TITLE
The --title (-t) option does not work

### ISSUE THREAD

**Issue by AKotov-dev** [dabisu/sakura#16]
Hello, **dabisu** (David Gómez). Thank you for your work. **Sakura** is a very good terminal and I am always happy to use it as the main terminal in my applications. I inform you that starting from the version **SAKURA_3_8_1** the option  `--title` (or `-t`) does not work in the terminal. Is there any way to fix this? Thanks.
```
# Version 3.8.1
> ./sakura --version
sakura version is 3.8.1
> ./sakura --title "1111"
Unknown option --title

# Version 3.8.5
> ./sakura -v
sakura version is 3.8.5
> ./sakura -t "1111"
Unknown option -t
```
With respect,
Alex

**Comment by ultratensai** [comment]
I'm having the same issue with 3.8.3

```
~ 
❯ sakura --version
sakura version is 3.8.3

~ 
❯ sakura -t hello 
Unknown option -t


```

**Comment by dabisu** [comment]
Hi Alex,

It's not that doesn't work, it's because the title command line option was removed starting from sakura-3.8.1. 

I think it's best to have the window title just display the current tab title. If you change your tab title to display something different from the CWD, that'll be what appears in the window title.

**Comment by dabisu** [comment]
Anyway, after checking some issues with others users, I'll put it back in 3.8.6
